version: "3.7"

services:
  oauth2-proxy:
    container_name: auth-sidecar
    image: quay.io/oauth2-proxy/oauth2-proxy:v7.6.0-alpine
    command: --config /oauth2-proxy.cfg
    volumes:
      - "./oauth2-proxy-nginx.cfg:/oauth2-proxy.cfg"
  nginx:
    container_name: partner-router
    image: nginx:1.27.0
    depends_on:
      - oauth2-proxy
      - notebook
    volumes:
      - ./nginx.conf:/etc/nginx/templates/default.conf.template
    ports:
      - 80:80
  notebook:
    container_name: notebook
    volumes:
      - ~/jupyter_work_dir:/home/jovyan/work
    image: quay.io/jupyter/base-notebook
    ports:
        - 8888:8888
    command: ["start-notebook.py", "--no-browser", "--NotebookApp.token=''", "--Notebook.password=''", "--NotebookApp.disable_check_xsrf=True"]
    restart: on-failure # Avoid flapping for local dev.
