version: "3.7"

services:
  oauth2-proxy:
    container_name: auth-sidecar
    image: quay.io/oauth2-proxy/oauth2-proxy:v7.6.0-alpine
    command: --config /oauth2-proxy.cfg
    volumes:
      - "./oauth2-proxy-nginx.cfg:/oauth2-proxy.cfg"
    restart: on-failure
  notebook:
    container_name: notebook
    volumes:
      - ~/jupyter_work_dir:/home/jovyan/work
    image: quay.io/jupyter/base-notebook
    ports:
        - 8888:8888
    command: ["start-notebook.py", "--no-browser", "--NotebookApp.token=''", "--Notebook.password=''", "--NotebookApp.disable_check_xsrf=True"]
    restart: on-failure # Avoid flapping for local dev.
  partner-cache:
    container_name: partner-cache
    image: redis/redis-stack-server:latest
    ports:
      - 6379:6379
    volumes:
      - ~/redisdata:/data
    restart: on-failure
  node-websocket-proxy:
    container_name: node-websocket-proxy
    image: node-websocket-proxy:latest
    volumes:
      - ~/.oci:/config/.oci
    ports:
      - 8891:8891
    restart: on-failure
  partner-router:
    container_name: partner-router
    image: nginx:1.27.0
    volumes:
      - ./nginx-conf:/etc/nginx
    ports:
      - 80:80
    restart: on-failure
    depends_on:
      - oauth2-proxy
      - notebook
      - partner-cache

    
